SOCIAL_AUTH_TWITTER_KEY = '565ez1lazYk4LIahW57fUYnpv'
SOCIAL_AUTH_TWITTER_SECRET = 'nwhRdD4n0mOTK7VProNvstPdoYrBGBMuf24Jmex0j7ceoamHTn'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'

